APS1 - Projeto de Aprendizado de Máquina

Classificador de falhas de aplicações industriais acionadas
por motores elétricos para máquinas rotativas

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, ConfusionMatrixDisplay

In [5]:
base_de_dados = pd.read_csv('Dataset APS1_Sinais Eletricos e Vibracao_csv.xls')
base_de_dados

,tempo_s,tipo_setup,I_entrada_A,P_entrada_W,I_saida_A,DesvPad_I_entrada_A,DesvPad _P_entrada_W,DesvPad _I_saida_A,Amp_I_entrada_A,Amp_P_entrada_W,Amp_I_saida_A,Kurtosis_I_entrada_A,Kurtosis_P_entrada_W,Kurtosis_I_saida_A,Mag_S1_f1_dBrms,Mag_S1_f2_dBrms,Mag_S1_f3_dBrms,Mag_S2_f1_dBrms,Mag_S2_f2_dBrms,Mag_S2_f3_dBrms
0,0.00,0.0,0.44905,63.67320,1.43660,0.042740,21.869566,0.113479,0.175,91.738,0.406,12.474475,15.435837,4.223108,-50.647991,-63.189443,-47.864704,-59.629807,-73.010381,-49.583755
1,0.08,0.0,0.44610,69.40320,1.67860,0.048945,1.600020,0.854342,0.227,7.359,3.843,20.070610,13.335535,16.966677,-50.696943,-63.340003,-48.313132,-59.591150,-72.360239,-49.473893
2,0.16,0.0,0.45175,69.11385,1.39950,0.042337,5.220348,0.284000,0.207,24.185,1.395,19.087723,7.345771,11.032327,-47.724322,-62.837371,-48.384219,-55.194912,-63.127903,-48.083630
3,0.24,0.0,0.43510,68.85665,1.39705,0.063224,3.437546,0.219507,0.228,16.040,0.973,6.869051,19.849528,9.136137,-47.652608,-62.613368,-48.768793,-55.275822,-63.310116,-47.937933
4,0.32,0.0,0.45055,70.52860,1.43375,0.048497,1.240032,0.111967,0.222,4.394,0.425,20.205840,2.325535,2.818658,-47.019446,-61.314274,-49.016646,-54.665312,-60.825200,-47.886619
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2500,39.68,4.0,0.46575,68.42795,1.59235,0.042147,8.058820,0.900427,0.199,37.403,4.276,5.486469,22.266532,21.582764,-33.195195,-52.502279,-41.610532,-37.874381,-49.147213,-42.417970
2501,39.76,4.0,0.44705,62.32815,1.57365,0.068987,15.876663,0.904702,0.231,62.159,4.218,5.237910,11.518238,21.593782,-33.360763,-52.868492,-42.054637,-37.995903,-49.251871,-42.703237
2502,39.84,4.0,0.47110,76.04075,1.77275,0.045194,34.799709,1.657858,0.191,184.906,7.810,9.874863,20.660427,6.075266,-33.497896,-53.300911,-42.289221,-38.129107,-48.947030,-42.896321
2503,39.92,4.0,0.47745,72.86850,1.39700,0.043033,0.826486,0.131019,0.194,2.893,0.383,21.320253,2.327027,1.904577,-33.581380,-53.601503,-42.527074,-38.258422,-48.618126,-42.420583
2504,40.00,4.0,0.48705,70.70715,1.51215,0.114987,12.366981,0.514260,0.608,41.761,2.476,10.119385,6.899001,20.098625,-33.599577,-53.697702,-42.686179,-38.335583,-48.344164,-41.969820

In [ ]:
from sklearn.model_selection import train_test_split  # usado para embaralhar e separar os dados de treino e teste
train_data, test_data = train_test_split(base_de_dados, test_size=0.20, random_state=1, shuffle=True)

# Exibir os dados de treinamento
train_data

,tempo_s,tipo_setup,I_entrada_A,P_entrada_W,I_saida_A,DesvPad_I_entrada_A,DesvPad _P_entrada_W,DesvPad _I_saida_A,Amp_I_entrada_A,Amp_P_entrada_W,Amp_I_saida_A,Kurtosis_I_entrada_A,Kurtosis_P_entrada_W,Kurtosis_I_saida_A,Mag_S1_f1_dBrms,Mag_S1_f2_dBrms,Mag_S1_f3_dBrms,Mag_S2_f1_dBrms,Mag_S2_f2_dBrms,Mag_S2_f3_dBrms
1861,28.64,3.0,0.47090,73.28460,1.67270,0.005902,2.734395,0.638069,0.026,13.039,2.538,6.374976,15.594765,10.141203,-45.170441,-53.925982,-47.875357,-49.081114,-57.088721,-46.723683
2207,16.24,4.0,0.44730,65.62895,1.45840,0.067206,0.870145,0.654890,0.272,3.501,3.237,9.148233,4.126347,19.063732,-32.480849,-50.244953,-42.052615,-37.931484,-52.755136,-43.544908
2173,13.52,4.0,0.47470,68.76740,1.46830,0.041376,0.939687,0.414083,0.186,3.894,1.994,16.681025,4.724549,16.791783,-33.216323,-50.255123,-41.487359,-37.886848,-52.364422,-42.007619
1727,17.92,3.0,0.48265,70.03370,1.50705,0.078498,15.566843,0.233007,0.413,91.453,1.071,19.167446,15.182148,8.204912,-44.798070,-55.648271,-50.160764,-50.591229,-59.157974,-46.700604
2243,19.12,4.0,0.47175,69.09600,1.57565,0.040828,1.276409,0.901468,0.199,3.965,4.233,15.190959,1.614825,21.867305,-32.223497,-51.864344,-43.834857,-37.189422,-52.309296,-42.386906
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
960,36.72,1.0,0.44775,63.13915,1.43420,0.037116,13.015825,0.141598,0.139,59.230,0.478,9.408040,20.836988,2.961490,-42.731132,-67.314880,-57.023627,-51.096640,-64.201754,-52.105158
905,32.32,1.0,0.43720,68.74225,1.43555,0.071936,11.564246,0.134524,0.231,52.443,0.391,6.323680,19.470823,2.271568,-42.728677,-69.699658,-55.788464,-50.513172,-63.871314,-52.213146
1096,7.52,2.0,0.52095,78.50375,1.27830,0.058204,26.754752,0.592369,0.308,121.103,2.757,9.679077,21.506311,21.080445,-36.833000,-41.026471,-39.065315,-39.344290,-40.103195,-42.157612
235,18.80,0.0,0.43570,65.50565,1.38210,0.054512,10.908854,0.172592,0.183,57.193,0.637,5.349926,20.974165,4.238516,-47.516891,-60.221978,-50.754946,-52.441689,-64.067560,-49.431601
1061,4.72,2.0,0.52900,91.51080,1.42345,0.007820,31.946030,0.201653,0.034,145.038,0.982,6.707849,22.970169,7.205496,-35.584746,-39.477958,-40.750839,-37.544537,-40.051182,-42.629467